//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public double Id { get; set; }
        public string OrderId { get; set; }
        public int ProId { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
        public double Amount { get; set; }
        public string ProductName { get; set; }
        public string ProductImg { get; set; }
        public string OrderType { get; set; }
        public string DeliveryStatus { get; set; }
    }
}
