//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildMenu
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Href { get; set; }
        public int MenuId { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
