//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigPaypal
    {
        public int Id { get; set; }
        public string Mode { get; set; }
        public Nullable<int> ConnectionTimeout { get; set; }
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
    }
}
