//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigDeliveryDay
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int NumOfDeliveryDay { get; set; }
        public int MinimumIntervalHour { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string DisplayText { get; set; }
        public Nullable<int> PerSlot { get; set; }
        public Nullable<bool> Weekday { get; set; }
        public Nullable<bool> Weekend { get; set; }
        public Nullable<bool> IsHoliday { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
