//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryScheduler
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string TimeSlot { get; set; }
        public string FromHour { get; set; }
        public string ToHour { get; set; }
        public double Rate { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> PerSlot { get; set; }
        public bool IsWeekday { get; set; }
        public bool IsWeekend { get; set; }
        public bool IsHoliday { get; set; }
        public bool IsActive { get; set; }
    }
}
