//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public Nullable<bool> UsingLayout { get; set; }
        public int CompanyId { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
    }
}
