//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS_Ecommerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    public partial class SBS_Entities : DbContext
    {
        public SBS_Entities()
            : base("name=SBS_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<BlogComment> BlogComments { get; set; }
        public virtual DbSet<ConfigChatting> ConfigChattings { get; set; }
        public virtual DbSet<ConfigPaypal> ConfigPaypals { get; set; }
        public virtual DbSet<ConfigSystem> ConfigSystems { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<EmailAccount> EmailAccounts { get; set; }
        public virtual DbSet<Marketing> Marketings { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<QueuedEmail> QueuedEmails { get; set; }
        public virtual DbSet<SBSLog> SBSLogs { get; set; }
        public virtual DbSet<ScheduledDelivery> ScheduledDeliveries { get; set; }
        public virtual DbSet<ScheduleEmail> ScheduleEmails { get; set; }
        public virtual DbSet<ShippingFee> ShippingFees { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAddress> UserAddresses { get; set; }
        public virtual DbSet<Wishlist> Wishlists { get; set; }

        public IQueryable<Blog> GetBlogs
        {
            get
            {
                return Blogs.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<BlogComment> GetBlogComments
        {
            get
            {
                return BlogComments.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<ConfigChatting> GetConfigChattings
        {
            get
            {
                return ConfigChattings.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<ConfigPaypal> GetConfigPaypals
        {
            get
            {
                return ConfigPaypals.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<ConfigSystem> GetConfigSystems
        {
            get
            {
                return ConfigSystems.Where(m => m.CompanyId == 1);
            }

        }
        public IQueryable<Coupon> GetCoupons
        {
            get
            {
                return Coupons.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<EmailAccount> GetEmailAccountss
        {
            get
            {
                return EmailAccounts.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<Marketing> GetMarketings
        {
            get
            {
                return Marketings.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<Order> GetOrders
        {
            get
            {
                return Orders.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<OrderDetail> GetOrderDetails
        {
            get
            {
                return OrderDetails.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<Payment> GetPaymentss
        {
            get
            {
                return Payments.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<QueuedEmail> GetQueuedEmails
        {
            get
            {
                return QueuedEmails.Where(m => m.CompanyId == 1);
            }

        }
        public IQueryable<SBSLog> GetSBSLogs
        {
            get
            {
                return SBSLogs.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<ScheduledDelivery> GetScheduledDeliveries
        {
            get
            {
                return ScheduledDeliveries.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<ScheduleEmail> GetScheduleEmails
        {
            get
            {
                return ScheduleEmails.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<ShippingFee> GetShippingFees
        {
            get
            {
                return ShippingFees.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<User> GetUsers
        {
            get
            {
                return Users.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<UserAddress> GetUserAddresses
        {
            get
            {
                return UserAddresses.Where(m => m.CompanyId == 1);
            }
        }
        public IQueryable<Wishlist> GetWishlists
        {
            get
            {
                return Wishlists.Where(m => m.CompanyId == 1);
            }
        }
    }
}
