//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightBased
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public double Min { get; set; }
        public double Max { get; set; }
        public double Rate { get; set; }
        public string UnitOfMass { get; set; }
        public string DeliveryCompany { get; set; }
        public string Country { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
