//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS_Ecommerce.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReview
    {
        public int Id { get; set; }
        public Nullable<int> UId { get; set; }
        public int ProId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> Rating { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string NameCreated { get; set; }
    }
}
