//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS_Ecommerce.Models.DTOs
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ConfigHolidayDTO
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Holiday Name")]
        public string HolidayName { get; set; }
        [Required]
        [DisplayName("Holiday Date")]
        public Nullable<System.DateTime> HolidayDate { get; set; }
        [DisplayName("Active")]
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string Description { get; set; }
        public int CompanyId { get; set; }
    }
}
